include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_SOC_PATH)/$(DBG_SOC)/soc.mk


obj-m	+= lidbg_soc_$(DBG_SOC).o
lidbg_soc_$(DBG_SOC)-objs := m_$(DBG_SOC).o lidbg_io_$(DBG_SOC).o  lidbg_ad_$(DBG_SOC).o lidbg_pwm_$(DBG_SOC).o


