#include $(DBG_DRIVERS_PATH)/config_$(DBG_SOC)
include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk

obj-y	:= acc/ bp_msg/ devices/ drivers_dbg/ fastboot/ suspend_monitor/ gps/ touchscreen/ videoin/ monkey/ hal/ interface/ msm8x26_devices/ powermanager/ dsi83/ lpc/
