include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk

obj-$(CONFIG_VIDEO_IN)	+= lidbg_videoin.o
lidbg_videoin-objs := lidbg_videoin_main.o tw9912.o TC358746XBG.o i2c_io.o video_init_config.o


